"use client";

import { useRef, useCallback } from "react";

interface PdfExportProps {
  destination: string;
  startDate: string;
  endDate: string;
  budget: string;
}

export default function PdfExport({ destination, startDate, endDate, budget }: PdfExportProps) {
  const generating = useRef(false);

  const handleExport = useCallback(async () => {
    if (generating.current) return;
    generating.current = true;

    try {
      // Dynamically import html2pdf (client-only)
      const html2pdf = (await import("html2pdf.js")).default;

      // Find the itinerary content
      const itineraryEl = document.querySelector("[data-itinerary-content]");
      if (!itineraryEl) {
        alert("No itinerary content found to export.");
        generating.current = false;
        return;
      }

      // Create a wrapper with cover page
      const wrapper = document.createElement("div");
      wrapper.style.cssText = "background: #fff; color: #1a1a2e; padding: 40px; font-family: Inter, sans-serif;";

      // Cover Page
      wrapper.innerHTML = `
        <div style="text-align: center; padding: 80px 40px; page-break-after: always;">
          <div style="font-size: 48px; margin-bottom: 16px;">✈️</div>
          <h1 style="font-size: 36px; font-weight: 700; color: #6366f1; margin-bottom: 8px; font-family: Sora, sans-serif;">
            TripPilot Itinerary
          </h1>
          <h2 style="font-size: 28px; font-weight: 600; color: #1a1a2e; margin-bottom: 32px;">
            ${destination}
          </h2>
          <div style="display: inline-flex; gap: 24px; font-size: 14px; color: #64748b; margin-bottom: 48px;">
            <span>📅 ${startDate} → ${endDate}</span>
            <span>💰 ${budget}</span>
          </div>
          <div style="margin-top: 64px; padding-top: 24px; border-top: 2px solid #e2e8f0;">
            <p style="font-size: 12px; color: #94a3b8;">
              Generated by TripPilot AI Travel Planner · ${new Date().toLocaleDateString()}
            </p>
          </div>
        </div>
      `;

      // Clone itinerary content with print-friendly styles
      const clone = itineraryEl.cloneNode(true) as HTMLElement;
      clone.style.cssText = "color: #1a1a2e; font-size: 14px; line-height: 1.7; padding: 20px 0;";

      // Fix colors for print
      clone.querySelectorAll("h1, h2, h3, strong").forEach((el) => {
        (el as HTMLElement).style.color = "#1a1a2e";
      });
      clone.querySelectorAll("h2").forEach((el) => {
        (el as HTMLElement).style.color = "#6366f1";
        (el as HTMLElement).style.borderBottomColor = "#e2e8f0";
      });
      clone.querySelectorAll("h3").forEach((el) => {
        (el as HTMLElement).style.background = "#f1f5f9";
        (el as HTMLElement).style.borderLeftColor = "#6366f1";
      });
      clone.querySelectorAll("em").forEach((el) => {
        (el as HTMLElement).style.color = "#0891b2";
      });

      wrapper.appendChild(clone);

      // Generate PDF
      const pdfMargin: [number, number, number, number] = [10, 15, 10, 15];
      const opt = {
        margin: pdfMargin,
        filename: `TripPilot-${destination.replace(/[^a-zA-Z0-9]/g, "-")}-Itinerary.pdf`,
        image: { type: "jpeg" as const, quality: 0.95 },
        html2canvas: { scale: 2, useCORS: true },
        jsPDF: { unit: "mm" as const, format: "a4" as const, orientation: "portrait" as const },
        pagebreak: { mode: ["avoid-all", "css", "legacy"] },
      };

      await html2pdf().set(opt).from(wrapper).save();
    } catch (err) {
      console.error("PDF export error:", err);
      alert("Failed to generate PDF. Please try again.");
    } finally {
      generating.current = false;
    }
  }, [destination, startDate, endDate, budget]);

  return (
    <button className="btn btn-secondary" onClick={handleExport} title="Download PDF">
      📄 Export PDF
    </button>
  );
}
